apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "route-management.fullname" . }}-celery-beat
  namespace: {{ include "route-management.namespace" . }}
  labels:
    {{- include "route-management.labels" . | nindent 4 }}
    app.kubernetes.io/component: celery-beat
spec:
  replicas: {{ .Values.celeryBeat.replicas }}
  selector:
    matchLabels:
      {{- include "route-management.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: celery-beat
  template:
    metadata:
      labels:
        {{- include "route-management.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: celery-beat
    spec:
      serviceAccountName: {{ include "route-management.serviceAccountName" . }}
      containers:
        - name: celery-beat
          image: "{{ .Values.images.backend.repository }}:{{ .Values.images.backend.tag }}"
          imagePullPolicy: {{ .Values.images.backend.pullPolicy }}
          command: ["celery", "-A", "config", "beat", "-l", "info"]
          envFrom:
            - configMapRef:
                name: {{ include "route-management.fullname" . }}-core-config
            - secretRef:
                name: {{ include "route-management.fullname" . }}-app-secrets
          resources:
            {{- toYaml .Values.celeryBeat.resources | nindent 12 }}
---
