{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "route-management.fullname" . }}-frontend
  namespace: {{ include "route-management.namespace" . }}
  labels:
    {{- include "route-management.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "route-management.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
{{- end }}
---
