{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "route-management.fullname" . }}-grafana
  namespace: {{ include "route-management.namespace" . }}
  labels:
    {{- include "route-management.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.grafana.persistence.size }}
{{- end }}
---
