apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "route-management.fullname" . }}-mongo
  namespace: {{ include "route-management.namespace" . }}
  labels:
    {{- include "route-management.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongo
spec:
  serviceName: {{ include "route-management.fullname" . }}-mongo
  replicas: {{ .Values.mongo.replicas }}
  selector:
    matchLabels:
      {{- include "route-management.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mongo
  template:
    metadata:
      labels:
        {{- include "route-management.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mongo
    spec:
      containers:
        - name: mongo
          image: "{{ .Values.images.mongo.repository }}:{{ .Values.images.mongo.tag }}"
          imagePullPolicy: {{ .Values.images.mongo.pullPolicy }}
          ports:
            - containerPort: {{ .Values.mongo.service.port }}
              name: mongo
          volumeMounts:
            - name: data
              mountPath: /data/db
          resources:
            {{- toYaml .Values.mongo.resources | nindent 12 }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.global.storageClass }}
        storageClassName: {{ .Values.global.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.mongo.persistence.size }}
---
