{{- if and .Values.rabbitmq.enabled (not .Values.externalServices.rabbitmq.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "route-management.fullname" . }}-rabbitmq
  namespace: {{ include "route-management.namespace" . }}
  labels:
    {{- include "route-management.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "route-management.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
  ports:
    - name: amqp
      port: {{ .Values.rabbitmq.service.amqpPort }}
      targetPort: amqp
    - name: management
      port: {{ .Values.rabbitmq.service.managementPort }}
      targetPort: management
---
{{- end }}
