apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "route-management.fullname" . }}-redis
  namespace: {{ include "route-management.namespace" . }}
  labels:
    {{- include "route-management.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  serviceName: {{ include "route-management.fullname" . }}-redis
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      {{- include "route-management.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        {{- include "route-management.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: redis
    spec:
      containers:
        - name: redis
          image: "{{ .Values.images.redis.repository }}:{{ .Values.images.redis.tag }}"
          imagePullPolicy: {{ .Values.images.redis.pullPolicy }}
          args: ["redis-server", "--appendonly", "yes"]
          ports:
            - containerPort: {{ .Values.redis.service.port }}
              name: redis
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.global.storageClass }}
        storageClassName: {{ .Values.global.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.redis.persistence.size }}
---
