from django.urls import path

from apps.company_admin.views import (
    AiSyncAPIView,
    CompanyAssignmentListAPIView,
    CompanyAdminDashboardOverviewAPIView,
    CompanyOperationExecutionDetailAPIView,
    CompanyOperationExecutionListAPIView,
    DriverAssignmentDetailAPIView,
    DriverAssignmentListCreateAPIView,
    DriverDetailAPIView,
    DriverListCreateAPIView,
    DriverResetPasswordAPIView,
    MediaUploadPresignAPIView,
    ProductDetailAPIView,
    ProductListCreateAPIView,
    LiveTrackingVehicleListAPIView,
    LiveTrackingVehicleDetailAPIView,
    RouteAvailableShopListAPIView,
    RouteDetailAPIView,
    RouteListCreateAPIView,
    RouteShopAddAPIView,
    RouteShopPositionUpdateAPIView,
    RouteShopRemoveAPIView,
    ShopDetailAPIView,
    ShopListCreateAPIView,
    ShopOwnerResetPasswordAPIView,
    RbacPermissionListAPIView,
    RbacRoleListCreateAPIView,
    RbacRoleDetailAPIView,
    RbacUserRoleListAssignAPIView,
    RbacUserRoleDetailAPIView,
    VehicleDetailAPIView,
    VehicleListCreateAPIView,
)


urlpatterns = [
    path("dashboard/overview/", CompanyAdminDashboardOverviewAPIView.as_view(), name="company-admin-dashboard-overview"),
    path("vehicles/", VehicleListCreateAPIView.as_view(), name="company-admin-vehicle-list-create"),
    path("vehicles/<uuid:vehicle_id>/", VehicleDetailAPIView.as_view(), name="company-admin-vehicle-detail"),
    path("media/presign/", MediaUploadPresignAPIView.as_view(), name="company-admin-media-presign"),
    path("products/", ProductListCreateAPIView.as_view(), name="company-admin-product-list-create"),
    path("products/<uuid:product_id>/", ProductDetailAPIView.as_view(), name="company-admin-product-detail"),
    path("shops/", ShopListCreateAPIView.as_view(), name="company-admin-shop-list-create"),
    path("shops/<uuid:shop_id>/", ShopDetailAPIView.as_view(), name="company-admin-shop-detail"),
    path("shops/<uuid:shop_id>/owner/reset-password/", ShopOwnerResetPasswordAPIView.as_view(), name="company-admin-shop-owner-reset-password"),
    path("drivers/", DriverListCreateAPIView.as_view(), name="company-admin-driver-list-create"),
    path("drivers/assignments/", CompanyAssignmentListAPIView.as_view(), name="company-admin-company-assignment-list"),
    path("operations/executions/", CompanyOperationExecutionListAPIView.as_view(), name="company-admin-operations-execution-list"),
    path(
        "operations/executions/<uuid:assignment_id>/",
        CompanyOperationExecutionDetailAPIView.as_view(),
        name="company-admin-operations-execution-detail",
    ),
    path("drivers/<uuid:driver_id>/", DriverDetailAPIView.as_view(), name="company-admin-driver-detail"),
    path("live-tracking/vehicles/", LiveTrackingVehicleListAPIView.as_view(), name="company-admin-live-tracking-vehicle-list"),
    path("live-tracking/vehicles/<uuid:vehicle_id>/", LiveTrackingVehicleDetailAPIView.as_view(), name="company-admin-live-tracking-vehicle-detail"),
    path("drivers/<uuid:driver_id>/reset-password/", DriverResetPasswordAPIView.as_view(), name="company-admin-driver-reset-password"),
    path(
        "drivers/<uuid:driver_id>/assignments/",
        DriverAssignmentListCreateAPIView.as_view(),
        name="company-admin-driver-assignment-list-create",
    ),
    path(
        "drivers/<uuid:driver_id>/assignments/<uuid:assignment_id>/",
        DriverAssignmentDetailAPIView.as_view(),
        name="company-admin-driver-assignment-detail",
    ),
    path("routes/", RouteListCreateAPIView.as_view(), name="company-admin-route-list-create"),
    path("routes/available-shops/", RouteAvailableShopListAPIView.as_view(), name="company-admin-route-available-shops"),
    path("routes/<uuid:route_id>/", RouteDetailAPIView.as_view(), name="company-admin-route-detail"),
    path("routes/<uuid:route_id>/shops/", RouteShopAddAPIView.as_view(), name="company-admin-route-shop-add"),
    path(
        "routes/<uuid:route_id>/shops/<uuid:shop_id>/",
        RouteShopRemoveAPIView.as_view(),
        name="company-admin-route-shop-remove",
    ),
    path(
        "routes/<uuid:route_id>/shops/<uuid:shop_id>/position/",
        RouteShopPositionUpdateAPIView.as_view(),
        name="company-admin-route-shop-position-update",
    ),
    path("rbac/permissions/", RbacPermissionListAPIView.as_view(), name="company-admin-rbac-permissions"),
    path("rbac/roles/", RbacRoleListCreateAPIView.as_view(), name="company-admin-rbac-roles"),
    path("rbac/roles/<uuid:role_id>/", RbacRoleDetailAPIView.as_view(), name="company-admin-rbac-role-detail"),
    path("rbac/user-roles/", RbacUserRoleListAssignAPIView.as_view(), name="company-admin-rbac-user-roles"),
    path("rbac/user-roles/<uuid:assignment_id>/", RbacUserRoleDetailAPIView.as_view(), name="company-admin-rbac-user-role-detail"),
    path("ai/sync/", AiSyncAPIView.as_view(), name="company-admin-ai-sync"),
]
