FROM node:20-slim AS builder

WORKDIR /app

COPY package*.json /app/
RUN npm install --no-audit --no-fund

COPY . /app
RUN npm run build

FROM nginx:1.27-alpine

COPY infra/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
