# Generated by Django 6.0.2 on 2026-02-24 07:53

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('mobile_number', models.CharField(db_index=True, max_length=20)),
                ('age', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('IN_ROUTE', 'In Route'), ('ON_LEAVE', 'On Leave')], db_index=True, default='AVAILABLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='company.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('route_name', models.CharField(max_length=120)),
                ('start_point', models.CharField(max_length=255)),
                ('end_point', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='company.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('owner_name', models.CharField(db_index=True, max_length=120)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shops/')),
                ('address', models.TextField(blank=True, default='')),
                ('landmark', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='company.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteShop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_shops', to='company_admin.route')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_assignments', to='company_admin.shop')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('number_plate', models.CharField(db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_ROUTE', 'On Route'), ('RENOVATION', 'Renovation')], db_index=True, default='AVAILABLE', max_length=20)),
                ('fuel_percentage', models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='company.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='ASSIGNED', max_length=20)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='company_admin.driver')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_assignments', to='company_admin.route')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_assignments', to='company_admin.vehicle')),
            ],
            options={
                'ordering': ['-scheduled_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['company', 'name'], name='company_adm_company_7a5405_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['company', 'status'], name='company_adm_company_2b52b5_idx'),
        ),
        migrations.AddConstraint(
            model_name='driver',
            constraint=models.UniqueConstraint(fields=('company', 'mobile_number'), name='uq_driver_company_mobile_number'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['company', 'route_name'], name='company_adm_company_e46720_idx'),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(fields=('company', 'route_name'), name='uq_route_company_route_name'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['company', 'name'], name='company_adm_company_2391f1_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['company', 'owner_name'], name='company_adm_company_d3de79_idx'),
        ),
        migrations.AddConstraint(
            model_name='shop',
            constraint=models.UniqueConstraint(fields=('company', 'name', 'owner_name'), name='uq_shop_company_name_owner'),
        ),
        migrations.AddIndex(
            model_name='routeshop',
            index=models.Index(fields=['route', 'position'], name='company_adm_route_i_f62db7_idx'),
        ),
        migrations.AddIndex(
            model_name='routeshop',
            index=models.Index(fields=['shop'], name='company_adm_shop_id_e23eb1_idx'),
        ),
        migrations.AddConstraint(
            model_name='routeshop',
            constraint=models.UniqueConstraint(fields=('route', 'position'), name='uq_route_shop_route_position'),
        ),
        migrations.AddConstraint(
            model_name='routeshop',
            constraint=models.UniqueConstraint(fields=('shop',), name='uq_route_shop_unique_shop'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('company', 'number_plate'), name='uq_vehicle_company_number_plate'),
        ),
        migrations.AddIndex(
            model_name='driverassignment',
            index=models.Index(fields=['driver', 'scheduled_at'], name='company_adm_driver__8ed4d6_idx'),
        ),
        migrations.AddIndex(
            model_name='driverassignment',
            index=models.Index(fields=['route', 'scheduled_at'], name='company_adm_route_i_e8aee7_idx'),
        ),
        migrations.AddIndex(
            model_name='driverassignment',
            index=models.Index(fields=['vehicle', 'scheduled_at'], name='company_adm_vehicle_117b5e_idx'),
        ),
        migrations.AddConstraint(
            model_name='driverassignment',
            constraint=models.UniqueConstraint(fields=('driver', 'scheduled_at'), name='uq_driver_assignment_driver_datetime'),
        ),
        migrations.AddConstraint(
            model_name='driverassignment',
            constraint=models.UniqueConstraint(fields=('vehicle', 'scheduled_at'), name='uq_driver_assignment_vehicle_datetime'),
        ),
    ]
