# Generated by Django 6.0.2 on 2026-02-25

from django.contrib.gis.db.models import fields
from django.contrib.gis.geos import Point
from django.db import migrations, models


def backfill_shop_point(apps, schema_editor):
    Shop = apps.get_model("company_admin", "Shop")
    for shop in Shop.objects.all().iterator():
        if shop.latitude is None or shop.longitude is None:
            continue
        shop.point = Point(float(shop.longitude), float(shop.latitude), srid=4326)
        if not shop.location_display_name:
            shop.location_display_name = shop.location or ""
        shop.save(update_fields=["point", "location_display_name", "updated_at"])


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):
    dependencies = [
        ("company_admin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="location_display_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="shop",
            name="point",
            field=fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.RunPython(backfill_shop_point, noop_reverse),
    ]
